name: Update IPTV Link

on:
  schedule:
    - cron: '0 * * * *' # এটি প্রতি ১ ঘণ্টা পর পর অটোমেটিক চলবে
  workflow_dispatch: # চাইলে আপনি নিজেও ম্যানুয়ালি রান করতে পারবেন

jobs:
  update-link:
    runs-edge: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install requests

    - name: Run Script
      run: python update_link.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add live.m3u
        git commit -m "Auto-updated IPTV link" || exit 0
        git push
